#!/bin/bash

# Repo Root
REPO_ROOT=$(git rev-parse --show-toplevel)

# High level parameters
AUTOMATION_FOLDER="automation"
AUTOMATION_PATH="$REPO_ROOT/$AUTOMATION_FOLDER"

DATA_FOLDER="data"
DATA_PATH="$REPO_ROOT/$DATA_FOLDER"

DOCS_FOLDER="docs"
DOCS_PATH="$REPO_ROOT/$DOCS_FOLDER"

SCRIPTS_FOLDER="scripts"
SCRIPTS_PATH="$REPO_ROOT/$SCRIPTS_FOLDER"

SRC_FOLDER="src"
SRC_PATH="$REPO_ROOT/$SRC_FOLDER"

TESTS_FOLDER="tests"
TESTS_PATH="$REPO_ROOT/$TESTS_FOLDER"

# Docs Subfolders
DOCS_RAW_FOLDER="raw"
DOCS_RAW_PATH="$DOCS_PATH/$DOCS_RAW_FOLDER"

DOCS_PDF_FOLDER="pdf"
DOCS_PDF_PATH="$DOCS_PATH/$DOCS_PDF_FOLDER"

# Scripts Subfolders
SCRIPTS_UTILS_FOLDER="utils"
SCRIPTS_UTILS_PATH="$SCRIPTS_PATH/$SCRIPTS_UTILS_FOLDER"
